### ISSUE TITLE
Network error does not crash the queue-worker, then 100% errors

### ISSUE THREAD

**Issue by milsanore** [fhteam/laravel-amqp#16]
Hi,
Firstly, as always, thanks for the great library.
My queue:worker had a network error when communicating with my RabbitMQ server. After this, all attempts to communicate with my RabbitMQ server cause errors. It feels like the queue:worker has a persistent connection to the RabbitMQ server, and that Laravel is preventing the queue:worker daemon from crashing (fault-tolerance?), so that the connection never gets re-established.

This is the full error message:

```
{
    "@fields": {
        "channel": "local",
        "git": {
            "branch": "master",
        },
        "level": 400,
        "memory_peak_usage": "22 MB",
        "memory_usage": "22 MB",
        "process_id": 13976
    },
    "@message": "
    	ErrorException: fwrite(): send of 43 bytes failed with errno=32 Broken pipe in /opt/fnx-ig/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:281
		Stack trace:
		#0 [internal function]: PhpAmqpLib\Wire\IO\StreamIO->error_handler(8, 'fwrite(): send ...', '/opt/fnx-ig/ven...', 281, Array)
		#1 /opt/fnx-ig/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(281): fwrite(Resource id #382, '\x01\x00\x01\x00\x00\x00#\x00<\x00F\x00\x00\eQ...', 8192)
		#2 /opt/fnx-ig/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(327): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00#\x00<\x00F\x00\x00\eQ...')
		#3 /opt/fnx-ig/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(448): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x01\x00\x00\x00#\x00<\x00F\x00\x00\eQ...')
		#4 /opt/fnx-ig/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(230): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
		#5 /opt/fnx-ig/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1000): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
		#6 /opt/fnx-ig/vendor/fhteam/laravel-amqp/src/Queue/AMQPQueue.php(326): PhpAmqpLib\Channel\AMQPChannel->basic_get('QUEUE_IG_INFLUE...')
		#7 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(241): Forumhouse\LaravelAmqp\Queue\AMQPQueue->pop('QUEUE_IG_INFLUE...')
		#8 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(104): Illuminate\Queue\Worker->getNextJob(Object(Forumhouse\LaravelAmqp\Queue\AMQPQueue), 'QUEUE_IG_INFLUE...')
		#9 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('amqp', 'QUEUE_IG_INFLUE...', Object(Illuminate\Queue\WorkerOptions))
		#10 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('amqp', 'QUEUE_IG_INFLUE...')
		#11 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
		#12 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
		#13 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
		#14 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
		#15 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
		#16 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
		#17 /opt/fnx-ig/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
		#18 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
		#19 /opt/fnx-ig/vendor/symfony/console/Application.php(888): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
		#20 /opt/fnx-ig/vendor/symfony/console/Application.php(224): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
		#21 /opt/fnx-ig/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
		#22 /opt/fnx-ig/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
		#23 /opt/fnx-ig/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
		#24 {main}",
    "@tags": [
        "local"
    ],
    "@timestamp": "2017-10-25T22:17:52.283927+00:00",
}
```

Note that it's an `ErrorException`. As far as I understand, that means a low-level PHP error that is being handled _like_ an exception. Maybe the problem stems from there.

@FractalizeR have you observed similar behaviour in your experience? 
Thanks for you help as always

**Comment by martianoff** [comment]
Hi, it is Laravel bug, i offered fix for them but they didn't apply https://github.com/laravel/framework/pull/20824. They want some refactoring unfortunately i don't have time to do it right now
Laravel worker goes to unlimited loop on network errors to ANY queue drivers/servers
You can still merge fix from my pull request manually

**Comment by milsanore** [comment]
Thanks, I'll close and chase on the Laravel side
